layout_spectrum: 0.5159511733800173
typography_spectrum: 0.5283220300916582
color:
  brandColors:
    - '#FF8000'
    - '#FFD933'
    - '#CCCC52'
    - '#8FB359'
    - '#192B33'
  brandStrength: 0.7571806928608567
  lightness: 0.9498517480678856
  saturation: 0.9021193992812186
  rhythmicContrast: 0.3923838119953871
content_rating:
  adult: false
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Phil Huff
  email: phil.huff@flysleepgo.com
  url: FlySleepGo.com
name: FlySleepGo
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Flights, hotels and rewards.'
purpose: []
