typography_spectrum: 0.36114
content_rating:
  adult: false
color:
  brandColors:
    - '#4263aa'
    - '#ece4d9'
    - '#b1bcd0'
    - '#a29785'
    - '#2b2b2b'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.76073
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Phil Huff
  email: phil.huff@flysleepgo.com
  url: FlySleepGo.com
name: FlySleepGo
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Flights, hotels and rewards.'
purpose: []
